baseURL = 'https://lionsos.org/'
languageCode = 'en-au'
title = 'LionsOS 0.3.0'
theme = 'hugo-book'

[markup.goldmark.renderer]
unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
  BookSection = 'docs'
  BookRepo = 'https://github.com/au-ts/lionsos_docs'
  LionsOsVersion = '0.3.0'
  MicrokitVersion = '2.0.1'
  SdfgenVersion = '0.23.1'

[menu]
[[menu.after]]
  name = "Source code"
  url = "https://github.com/au-ts/lionsos"
  weight = 10
